version: "3.3"
services:
  devs:
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - "./home:/home"
      - "../results:/results"
      - "../mass_roads:/mass_roads"
      - "../dataset:/dataset"
    environment:
      - SHELL=/bin/bash
      - TF_CPP_MIN_LOG_LEVEL=2
    image: straxfromibr/jupyterlab_tf
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
