version: "3.3"
services:
  devs:
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - "./home:/home"
      - "../results:/results"
    image: jupyterlab_tf
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
